### ISSUE TITLE
(require crypto/libcrypto) Fails On Fedora 26

### ISSUE THREAD

**Issue by RayRacine** [rmculpepper/crypto#2]
In crypto-lib/private/libcrypto/pkey.rkt the function builtin-curve-nids maps `car` over the curve-table ,which as documented, may have a #f value for some key.  

;; curve-table : Hash[String => (cons Nat String/#f)] ;; <-- #f is possible and must be accounted for
(define curve-table (make-hash))

On my Fedora 26 system this is in fact the case and the `map` call in builtin-curve-nids fails, which in turn causes a (require crypto/libcrypto) to fail.

A fix would be to filter #f values and leaving only the pairs for map car to operate on.

(define builtin-curve-nids (map car (filter (λ (x) x) (hash-values curve-table))))

**Comment by rmculpepper** [comment]
Thanks for the report! The `#f` in the contract comment is in place of the string, not the whole pair. The problem seems to be that I was adding curve alias mappings even when libcrypto didn't support any of the names. I just pushed what I think is a fix, but I can't test it on Fedora 26 right now. Let me know if the problem still occurs.
